#!/usr/bin/env node

const fs = require('fs');
const glob = require('glob');
const path = require('path');
const stringify = require('json-stable-stringify');

var args = process.argv.slice(2);

if (!args.length) {
    process.stdout.write('You must specify the messages dir generated by babel-plugin-react-intl.\n');
    process.exit(1);
}

const dir = args.shift()

glob.sync(`${dir}/**/*.json`).forEach(filename => fs.writeFileSync(filename, stringify(JSON.parse(fs.readFileSync(filename, 'utf8')), {space: '    '})))
